# meshtui/themes.py
from prompt_toolkit.styles import Style

try:
    from themes import THEMES as _EXTERNAL_THEMES  # noqa: F401
    THEMES = _EXTERNAL_THEMES
except ImportError:
    THEMES = {
        'default': {
            "frame": "bg:#000080 fg:ansiwhite",
            "frame.border": "fg:ansibrightblue",
            "frame.label": "fg:ansiyellow bold",
            "frame.focused": "bg:#000080 fg:ansiyellow bold",
            "frame.focused.border": "fg:ansiyellow",
            "frame.focused.label": "fg:ansibrightyellow bold",
            "header": "bg:ansibrightblue fg:ansiblack",
            "statusbar": "bg:ansiblue fg:ansiwhite",
            "text-area": "bg:#000040 fg:ansiwhite",
            "text-area.prompt": "fg:ansicyan",
            "list.item.selected": "bg:ansigray fg:#000000",
            "list.item.focused": "bg:ansiwhite fg:ansiblack",
            "message.local": "fg:ansicyan",
            "message.remote": "fg:ansiwhite",
            "message.dm": "fg:ansibrightmagenta",
            "message.error": "fg:ansired bold",
            "node.notification": "fg:ansiyellow bold",
            "button": "bg:ansigray fg:ansiblack",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:ansiblue",
            "map.land": "fg:ansigreen",
            "map.structure": "fg:ansibrightblack",
            "msg.pending": "fg:#aaaaaa",
            "msg.sent":    "fg:#8888ff",
            "msg.retry":   "fg:#ffd000",
            "msg.acked":   "fg:#00d000",
            "msg.failed":  "fg:#ff4040",
            "msg.body":    "",
        },
        'forest': {
            "frame": "bg:#002b36 fg:#839496",
            "frame.border": "fg:#586e75",
            "frame.label": "fg:#b58900 bold",
            "frame.focused": "bg:#002b36 fg:#b58900 bold",
            "frame.focused.border": "fg:#b58900",
            "frame.focused.label": "fg:#b58900 bold",
            "header": "bg:#073642 fg:#eee8d5",
            "statusbar": "bg:#002b36 fg:#93a1a1",
            "text-area": "bg:#001f28 fg:#839496",
            "text-area.prompt": "fg:#2aa198",
            "list.item.selected": "bg:#586e75 fg:#eee8d5",
            "list.item.focused": "bg:#93a1a1 fg:#002b36",
            "message.local": "fg:#2aa198",
            "message.remote": "fg:#839496",
            "message.dm": "fg:#d33682",
            "message.error": "fg:#dc322f bold",
            "node.notification": "fg:#b58900 bold",
            "button": "bg:#586e75 fg:#eee8d5",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#268bd2",
            "map.land": "fg:#859900",
            "map.structure": "fg:#657b83",
        },
        'windows_95': {
            "frame": "bg:#c0c0c0 fg:#000000",
            "frame.border": "fg:#808080",
            "frame.label": "fg:#000080 bold",
            "frame.focused": "bg:#c0c0c0 fg:#000080 bold",
            "frame.focused.border": "fg:#000080",
            "frame.focused.label": "fg:#000080 bold",
            "header": "bg:#000080 fg:#ffffff",
            "statusbar": "bg:#c0c0c0 fg:#000000",
            "text-area": "bg:#ffffff fg:#000000",
            "text-area.prompt": "fg:#008080",
            "list.item.selected": "bg:#000080 fg:#ffffff",
            "list.item.focused": "bg:#000080 fg:#ffffff reverse",
            "message.local": "fg:#008000",
            "message.remote": "fg:#000000",
            "message.dm": "fg:#800000",
            "message.error": "fg:#ff0000 bold",
            "node.notification": "fg:#000080 bold",
            "button": "bg:#c0c0c0 fg:#000000",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#0000ff",
            "map.land": "fg:#008000",
            "map.structure": "fg:#808080",
        },
        'matrix': {
            "frame": "bg:#000000 fg:#00ff00",
            "frame.border": "fg:#008800",
            "frame.label": "fg:#00ff00 bold",
            "frame.focused": "bg:#000000 fg:#00ff00 bold",
            "frame.focused.border": "fg:#00ff00",
            "frame.focused.label": "fg:#00ff00 bold",
            "header": "bg:#005500 fg:#ffffff",
            "statusbar": "bg:#003300 fg:#00ff00",
            "text-area": "bg:#001100 fg:#00ff00",
            "text-area.prompt": "fg:ansibrightgreen",
            "list.item.selected": "bg:#00ff00 fg:#000000",
            "list.item.focused": "bg:#00ff00 fg:#000000 reverse",
            "message.local": "fg:ansibrightgreen",
            "message.remote": "fg:#00ff00",
            "message.dm": "fg:#ffffff",
            "message.error": "fg:#ffffff bg:#550000 bold",
            "node.notification": "fg:#00ff00 bold",
            "button": "bg:#005500 fg:#ffffff",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#008800",
            "map.land": "fg:#00ff00",
            "map.structure": "fg:#005500",
        },
        'cyberpunk': {
            "frame": "bg:#0c0c1e fg:#c4c4ff",
            "frame.border": "fg:#ff00ff",
            "frame.label": "fg:#ffff00 bold",
            "frame.focused": "bg:#0c0c1e fg:#ffff00 bold",
            "frame.focused.border": "fg:#ffff00",
            "frame.focused.label": "fg:#ffff00 bold",
            "header": "bg:#ff00ff fg:#000000",
            "statusbar": "bg:#3d003d fg:#c4c4ff",
            "text-area": "bg:#1c1c3e fg:#c4c4ff",
            "text-area.prompt": "fg:#00ffff",
            "list.item.selected": "bg:#ffff00 fg:#000000",
            "list.item.focused": "bg:#ffff00 fg:#000000 reverse",
            "message.local": "fg:#00ffff",
            "message.remote": "fg:#c4c4ff",
            "message.dm": "fg:#ff00ff",
            "message.error": "fg:#ff5555 bold",
            "node.notification": "fg:#ffff00 bold",
            "button": "bg:#ffff00 fg:#000000",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#00ffff",
            "map.land": "fg:#ff00ff",
            "map.structure": "fg:#c4c4ff",
        },
        'solarized_dark': {
            "frame": "bg:#002b36 fg:#839496",
            "frame.border": "fg:#586e75",
            "frame.label": "fg:#b58900",
            "frame.focused": "bg:#002b36 fg:#b58900",
            "frame.focused.border": "fg:#b58900",
            "frame.focused.label": "fg:#b58900 bold",
            "header": "bg:#073642 fg:#eee8d5",
            "statusbar": "bg:#002b36 fg:#93a1a1",
            "text-area": "bg:#001f28 fg:#839496",
            "text-area.prompt": "fg:#268bd2",
            "list.item.selected": "bg:#93a1a1 fg:#002b36",
            "list.item.focused": "bg:#eee8d5 fg:#002b36",
            "message.local": "fg:#2aa198",
            "message.remote": "fg:#839496",
            "message.dm": "fg:#d33682",
            "message.error": "fg:#dc322f bold",
            "node.notification": "fg:#cb4b16",
            "button": "bg:#586e75 fg:#eee8d5",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#268bd2",
            "map.land": "fg:#859900",
            "map.structure": "fg:#93a1a1",
        },
        'dracula': {
            "frame": "bg:#282a36 fg:#f8f8f2",
            "frame.border": "fg:#44475a",
            "frame.label": "fg:#ff79c6",
            "frame.focused": "bg:#282a36 fg:#ff79c6",
            "frame.focused.border": "fg:#ff79c6",
            "frame.focused.label": "fg:#ff79c6 bold",
            "header": "bg:#44475a fg:#f8f8f2",
            "statusbar": "bg:#1e1f29 fg:#f8f8f2",
            "text-area": "bg:#21222c fg:#f8f8f2",
            "text-area.prompt": "fg:#bd93f9",
            "list.item.selected": "bg:#44475a fg:#f8f8f2",
            "list.item.focused": "bg:#6272a4 fg:#f8f8f2",
            "message.local": "fg:#50fa7b",
            "message.remote": "fg:#f8f8f2",
            "message.dm": "fg:#ff79c6",
            "message.error": "fg:#ff5555 bold",
            "node.notification": "fg:#f1fa8c",
            "button": "bg:#44475a fg:#f8f8f2",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#bd93f9",
            "map.land": "fg:#50fa7b",
            "map.structure": "fg:#6272a4",
        },
        'monokai': {
            "frame": "bg:#272822 fg:#f8f8f2",
            "frame.border": "fg:#75715e",
            "frame.label": "fg:#e6db74",
            "frame.focused": "bg:#272822 fg:#e6db74",
            "frame.focused.border": "fg:#e6db74",
            "frame.focused.label": "fg:#e6db74 bold",
            "header": "bg:#75715e fg:#272822",
            "statusbar": "bg:#3e3d32 fg:#f8f8f2",
            "text-area": "bg:#2e2e2e fg:#f8f8f2",
            "text-area.prompt": "fg:#a6e22e",
            "list.item.selected": "bg:#f92672 fg:#f8f8f2",
            "list.item.focused": "bg:#a6e22e fg:#272822",
            "message.local": "fg:#a6e22e",
            "message.remote": "fg:#f8f8f2",
            "message.dm": "fg:#66d9ef",
            "message.error": "fg:#f92672 bold",
            "node.notification": "fg:#fd971f",
            "button": "bg:#75715e fg:#272822",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#66d9ef",
            "map.land": "fg:#a6e22e",
            "map.structure": "fg:#f8f8f2",
        },
        'gruvbox': {
            "frame": "bg:#282828 fg:#ebdbb2",
            "frame.border": "fg:#fabd2f",
            "frame.label": "fg:#d79921 bold",
            "frame.focused": "bg:#282828 fg:#d79921 bold",
            "frame.focused.border": "fg:#d79921",
            "frame.focused.label": "fg:#d79921 bold",
            "header": "bg:#458588 fg:#ebdbb2",
            "statusbar": "bg:#3c3836 fg:#fabd2f",
            "text-area": "bg:#1d2021 fg:#ebdbb2",
            "text-area.prompt": "fg:#b8bb26",
            "list.item.selected": "bg:#fabd2f fg:#282828",
            "list.item.focused": "bg:#ebdbb2 fg:#282828",
            "message.local": "fg:#b8bb26",
            "message.remote": "fg:#ebdbb2",
            "message.dm": "fg:#b16286",
            "message.error": "fg:#fb4934 bold",
            "node.notification": "fg:#fe8019 bold",
            "button": "bg:#fabd2f fg:#282828",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#458588",
            "map.land": "fg:#b8bb26",
            "map.structure": "fg:#928374",
        },
        'night_owl': {
            "frame": "bg:#011627 fg:#d6deeb",
            "frame.border": "fg:#82aaff",
            "frame.label": "fg:#c792ea bold",
            "frame.focused": "bg:#011627 fg:#c792ea bold",
            "frame.focused.border": "fg:#c792ea",
            "frame.focused.label": "fg:#c792ea bold",
            "header": "bg:#011627 fg:#82aaff",
            "statusbar": "bg:#011221 fg:#d6deeb",
            "text-area": "bg:#011221 fg:#d6deeb",
            "text-area.prompt": "fg:#7fdbca",
            "list.item.selected": "bg:#82aaff fg:#011627",
            "list.item.focused": "bg:#addb67 fg:#011627",
            "message.local": "fg:#7fdbca",
            "message.remote": "fg:#d6deeb",
            "message.dm": "fg:#c792ea",
            "message.error": "fg:#ef5350 bold",
            "node.notification": "fg:#f78c6c bold",
            "button": "bg:#82aaff fg:#011627",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#82aaff",
            "map.land": "fg:#addb67",
            "map.structure": "fg:#637777",
        },
        'one_dark': {
            "frame": "bg:#282c34 fg:#abb2bf",
            "frame.border": "fg:#61afef",
            "frame.label": "fg:#e5c07b bold",
            "frame.focused": "bg:#282c34 fg:#e5c07b bold",
            "frame.focused.border": "fg:#e5c07b",
            "frame.focused.label": "fg:#e5c07b bold",
            "header": "bg:#21252b fg:#61afef",
            "statusbar": "bg:#21252b fg:#abb2bf",
            "text-area": "bg:#282c34 fg:#abb2bf",
            "text-area.prompt": "fg:#98c379",
            "list.item.selected": "bg:#61afef fg:#282c34",
            "list.item.focused": "bg:#abb2bf fg:#282c34",
            "message.local": "fg:#98c379",
            "message.remote": "fg:#abb2bf",
            "message.dm": "fg:#c678dd",
            "message.error": "fg:#e06c75 bold",
            "node.notification": "fg:#e5c07b bold",
            "button": "bg:#61afef fg:#282c34",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#61afef",
            "map.land": "fg:#98c379",
            "map.structure": "fg:#5c6370",
        },
        'vaporwave': {
            "frame": "bg:#2d1b3b fg:#f7c1ff",
            "frame.border": "fg:#00fff7",
            "frame.label": "fg:#f7c1ff bold",
            "frame.focused": "bg:#2d1b3b fg:#f7c1ff bold",
            "frame.focused.border": "fg:#f7c1ff",
            "frame.focused.label": "fg:#f7c1ff bold",
            "header": "bg:#ff71ce fg:#2d1b3b",
            "statusbar": "bg:#01cdfe fg:#f7c1ff",
            "text-area": "bg:#1f1147 fg:#f7c1ff",
            "text-area.prompt": "fg:#05ffa1",
            "list.item.selected": "bg:#05ffa1 fg:#2d1b3b",
            "list.item.focused": "bg:#ff71ce fg:#2d1b3b",
            "message.local": "fg:#01cdfe",
            "message.remote": "fg:#f7c1ff",
            "message.dm": "fg:#ff71ce",
            "message.error": "fg:#ff71ce bold",
            "node.notification": "fg:#05ffa1 bold",
            "button": "bg:#05ffa1 fg:#2d1b3b",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#01cdfe",
            "map.land": "fg:#ff71ce",
            "map.structure": "fg:#f7c1ff",
        },
        'nord': {
            "frame": "bg:#2e3440 fg:#d8dee9",
            "frame.border": "fg:#88c0d0",
            "frame.label": "fg:#ebcb8b bold",
            "frame.focused": "bg:#2e3440 fg:#ebcb8b bold",
            "frame.focused.border": "fg:#ebcb8b",
            "frame.focused.label": "fg:#ebcb8b bold",
            "header": "bg:#3b4252 fg:#8fbcbb",
            "statusbar": "bg:#3b4252 fg:#d8dee9",
            "text-area": "bg:#2e3440 fg:#d8dee9",
            "text-area.prompt": "fg:#a3be8c",
            "list.item.selected": "bg:#88c0d0 fg:#2e3440",
            "list.item.focused": "bg:#d8dee9 fg:#2e3440",
            "message.local": "fg:#a3be8c",
            "message.remote": "fg:#d8dee9",
            "message.dm": "fg:#b48ead",
            "message.error": "fg:#bf616a bold",
            "node.notification": "fg:#ebcb8b bold",
            "button": "bg:#88c0d0 fg:#2e3440",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#81a1c1",
            "map.land": "fg:#a3be8c",
            "map.structure": "fg:#4c566a",
        },
        'tokyo_night': {
            "frame": "bg:#1a1b26 fg:#c0caf5",
            "frame.border": "fg:#7aa2f7",
            "frame.label": "fg:#bb9af7 bold",
            "frame.focused": "bg:#1a1b26 fg:#bb9af7 bold",
            "frame.focused.border": "fg:#bb9af7",
            "frame.focused.label": "fg:#bb9af7 bold",
            "header": "bg:#24283b fg:#7aa2f7",
            "statusbar": "bg:#24283b fg:#c0caf5",
            "text-area": "bg:#1a1b26 fg:#c0caf5",
            "text-area.prompt": "fg:#7dcfff",
            "list.item.selected": "bg:#7aa2f7 fg:#1a1b26",
            "list.item.focused": "bg:#c0caf5 fg:#1a1b26",
            "message.local": "fg:#7dcfff",
            "message.remote": "fg:#c0caf5",
            "message.dm": "fg:#bb9af7",
            "message.error": "fg:#f7768e bold",
            "node.notification": "fg:#e0af68 bold",
            "button": "bg:#7aa2f7 fg:#1a1b26",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#7aa2f7",
            "map.land": "fg:#9ece6a",
            "map.structure": "fg:#565f89",
        },
        'github_dark': {
            "frame": "bg:#0d1117 fg:#c9d1d9",
            "frame.border": "fg:#30363d",
            "frame.label": "fg:#79c0ff bold",
            "frame.focused": "bg:#0d1117 fg:#79c0ff bold",
            "frame.focused.border": "fg:#79c0ff",
            "frame.focused.label": "fg:#79c0ff bold",
            "header": "bg:#161b22 fg:#c9d1d9",
            "statusbar": "bg:#161b22 fg:#79c0ff",
            "text-area": "bg:#0d1117 fg:#c9d1d9",
            "text-area.prompt": "fg:#a5d6ff",
            "list.item.selected": "bg:#21262d fg:#79c0ff",
            "list.item.focused": "bg:#c9d1d9 fg:#0d1117",
            "message.local": "fg:#a5d6ff",
            "message.remote": "fg:#c9d1d9",
            "message.dm": "fg:#d2a8ff",
            "message.error": "fg:#ff7b72 bold",
            "node.notification": "fg:#79c0ff bold",
            "button": "bg:#21262d fg:#79c0ff",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#79c0ff",
            "map.land": "fg:#85e89d",
            "map.structure": "fg:#484f58",
        },
        'retro_terminal': {
            "frame": "bg:#101010 fg:#33ff33",
            "frame.border": "fg:#00ff00",
            "frame.label": "fg:#33ff33 bold",
            "frame.focused": "bg:#101010 fg:#33ff33 bold",
            "frame.focused.border": "fg:#33ff33",
            "frame.focused.label": "fg:#33ff33 bold",
            "header": "bg:#222222 fg:#33ff33",
            "statusbar": "bg:#191919 fg:#00ff00",
            "text-area": "bg:#101010 fg:#33ff33",
            "text-area.prompt": "fg:#00ff00",
            "list.item.selected": "bg:#00ff00 fg:#191919",
            "list.item.focused": "bg:#33ff33 fg:#101010",
            "message.local": "fg:#00ff00",
            "message.remote": "fg:#33ff33",
            "message.dm": "fg:#ff00ff",
            "message.error": "fg:#ff0000 bold",
            "node.notification": "fg:#ffff00 bold",
            "button": "bg:#00ff00 fg:#191919",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#0000ff",
            "map.land": "fg:#33ff33",
            "map.structure": "fg:#808080",
        },
        'powerline': {
            "frame": "bg:#222d31 fg:#b7c5d3",
            "frame.border": "fg:#ec7600",
            "frame.label": "fg:#fbb829 bold",
            "frame.focused": "bg:#222d31 fg:#fbb829 bold",
            "frame.focused.border": "fg:#fbb829",
            "frame.focused.label": "fg:#fbb829 bold",
            "header": "bg:#344449 fg:#fbb829",
            "statusbar": "bg:#232e34 fg:#fbb829",
            "text-area": "bg:#232e34 fg:#b7c5d3",
            "text-area.prompt": "fg:#00ede1",
            "list.item.selected": "bg:#fbb829 fg:#232e34",
            "list.item.focused": "bg:#b7c5d3 fg:#222d31",
            "message.local": "fg:#00ede1",
            "message.remote": "fg:#b7c5d3",
            "message.dm": "fg:#ec7600",
            "message.error": "fg:#e74856 bold",
            "node.notification": "fg:#ec7600 bold",
            "button": "bg:#fbb829 fg:#232e34",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#0095ff",
            "map.land": "fg:#a6e22e",
            "map.structure": "fg:#4e5a5e",
        },
        'oceanic': {
            "frame": "bg:#223344 fg:#c5dfff",
            "frame.border": "fg:#44b9b9",
            "frame.label": "fg:#ffd700 bold",
            "frame.focused": "bg:#223344 fg:#ffd700 bold",
            "frame.focused.border": "fg:#ffd700",
            "frame.focused.label": "fg:#ffd700 bold",
            "header": "bg:#1b2b34 fg:#44b9b9",
            "statusbar": "bg:#223344 fg:#ffd700",
            "text-area": "bg:#1b2b34 fg:#c5dfff",
            "text-area.prompt": "fg:#00ffff",
            "list.item.selected": "bg:#44b9b9 fg:#1b2b34",
            "list.item.focused": "bg:#c5dfff fg:#223344",
            "message.local": "fg:#00ffff",
            "message.remote": "fg:#c5dfff",
            "message.dm": "fg:#ffae57",
            "message.error": "fg:#ff5c57 bold",
            "node.notification": "fg:#ffd700 bold",
            "button": "bg:#44b9b9 fg:#1b2b34",
            "btn": "reverse",
            "btn.hover": "reverse bold",
            "btn.active": "reverse underline",
            "map.water": "fg:#00ffff",
            "map.land": "fg:#99cc33",
            "map.structure": "fg:#667788",
        },
    }

_BASE_KEYS = {
    "frame": "",
    "frame.border": "",
    "frame.label": "",
    "frame.focused": "",
    "frame.focused.border": "",
    "frame.focused.label": "",
    "header": "",
    "statusbar": "",
    "statusbar.notification": "bg:ansibrightyellow fg:ansiblack",
    "text-area": "",
    "text-area.prompt": "",
    "list.item.selected": "",
    "list.item.focused": "",
    "message.local": "",
    "message.remote": "",
    "message.dm": "",
    "message.error": "",
    "node.notification": "",
    "button": "",
    "btn": "",
    "btn.hover": "",
    "btn.active": "",
    "map.water": "",
    "map.land": "",
    "map.structure": "",
    "label": "bold",
}

def _style_from_dict(d: dict) -> Style:
    s = dict(_BASE_KEYS)
    s.update({k: v for k, v in d.items() if k in s})
    return Style.from_dict(s)

class ThemeManager:
    def __init__(self, initial: str | None = None):
        names = list(THEMES.keys())
        self._names = names or ["default"]
        self._idx = max(0, self._names.index(initial)) if initial in self._names else 0
        self._style = _style_from_dict(THEMES[self.name])

    @property
    def name(self) -> str:
        return self._names[self._idx]

    @property
    def style(self) -> Style:
        return self._style

    def set(self, name: str) -> None:
        if name in THEMES:
            self._idx = self._names.index(name)
            self._style = _style_from_dict(THEMES[name])

    def cycle_next(self) -> str:
        self._idx = (self._idx + 1) % len(self._names)
        self._style = _style_from_dict(THEMES[self.name])
        return self.name

    def names(self) -> list[str]:
        return list(self._names)
